close all
clear all

fname_solo = {'20220120_ana_CPRsolo_block1_tbl.mat',...
    '20220214_sol_CPRsolo_block1_tbl.mat',...
    '20220126_dih_CPRsolo_block1_tbl.mat',...
    '20220201_mam_CPRsolo_block1_tbl.mat',...
    '20220128_nak_CPRsolo_block1_tbl.mat',...
    '20220223_cah_CPRsolo_block1_tbl.mat',...
    '20220315_syn_CPRsolo_block1_tbl.mat',...
    '20220225_anb_CPRsolo_block1_tbl.mat',...
    '20220325_ant_CPRsolo_block1_tbl.mat',...
    '20220216_tos_CPRsolo_block1_tbl.mat',...
    '20220312_seo_CPRsolo_block1_tbl.mat',...
    '20220222_anm_CPRsolo_block1_tbl.mat'}; % SOLO DATA

tbl_pop                     = [];
pth                         = '/Users/fschneider/Documents/CPR_psychophysics/';

for iSub = 1:size(fname_solo,2)
    disp(['Subject_' num2str(iSub)])
    clear t
    tmp1                    = load([pth fname_solo{iSub}(10:12) '/summary/' fname_solo{iSub}]);
    fname_solo{iSub}(end-8) = '2';
    tmp2                    = load([pth fname_solo{iSub}(10:12) '/summary/' fname_solo{iSub}]);
    t                       = [tmp1.t; tmp2.t];
    tbl_pop                 = [tbl_pop; t];      
end

tbl_pop(:,24:end) = [];
writetable(tbl_pop,'/Users/fschneider/Desktop/solo_exmple_data.csv') 
save(['/Users/fschneider/Desktop/solo_exmple_data.mat'], 'tbl_pop', '-v7.3')