%% CPR main analysis
% Processes and analyses CPR electrophysiology data.
%
% Required per recording:
%   .MWK2   MWorks data file
%   .MAT    spike files generated by ULTRAsort
%
% Pipeline stages (in order):
%   1. Write wideband data
%   2. Check clipping
%   3. ULTRAsort preprocessing (no denoising)
%   4. ULTRAsort spike sorting (negative threshold channels only)
%   5. PHY_preprocessing  — import, sync, RF characterisation, CPR spikes
%   6. PHY_quality_assessment — onset response test, inclusion flags
%   7. PHY_sort_spikes_by_state — state-aligned spike trains
%
% Felix Schneider, CNL
%
% Version history
%   1.0  (fxs 2025-09-05)  Initial version.
%   1.1  (fxs 2025-xx-xx)  RF_characterisation integrated into preprocessing.
%
% TO DO
%   (1) Drift analysis — check FR stability over time
%   (2) Optional spike-free (behaviour-only) mode

clear; close all;

addpath('/Users/cnl/Desktop/CPR/code');


% =========================================================================
%% Configuration
% =========================================================================

cfg_pth      = '/Users/cnl/Desktop/CPR/code/felix_nhp_solo.cfg';
source_dir   = '/Users/cnl/Documents/DATA/Nilan/';
preproc_flag = true;    % true  = run full preprocessing pipeline
                        % false = load previously saved summary file
import_flag  = false;   % true  = import from .mwk2 and write .h5
                        % false = load existing .h5


% =========================================================================
%% Recording list
% =========================================================================
% Each entry is a full recording identifier string.
% Recordings excluded from the list are documented below with the reason.

rec_lst = {
    '20250924_nil_CPR_block1_phy4_rec059_fxs', ...
    '20250925_nil_CPR_block1_phy4_rec060_fxs', ...
    '20250926_nil_CPR_block1_phy4_rec061_fxs', ...
    '20251204_nil_CPR_block1_phy4_rec068_fxs', ...
    '20260128_nil_CPR_block1_phy4_rec074_ann', ...
    '20260123_nil_CPR_block2_phy4_rec073_ann'};

% Excluded recordings:
%   20250807_nil_..._rec045  onset transients before t=0
%   20250903_nil_..._rec050  (commented out — under review)
%   20251001_nil_..._rec063  sorted but sync issues
%   20251024_nil_..._rec066  channel clipping
%   20251205_nil_..._rec069  no A/D data
%   20251211_nil_..._rec070  no A/D data


% =========================================================================
%% Main processing loop
% =========================================================================

for iRec = 1:numel(rec_lst)

    rec_name = rec_lst{iRec};
    rec_info = split(rec_name, '_');

    % Build destination directory from date, recording number, and block
    dest_dir = fullfile('/Users/cnl/Documents/DATA/Nilan/spike_sorting/', ...
                        sprintf('%s_%s_%s', rec_info{1}, rec_info{6}, rec_info{4}), '/');

    summary_file = fullfile(dest_dir, ['summary_' rec_name '.mat']);
    state_file   = fullfile(dest_dir, ['state_responses_' rec_name '.mat']);

    fprintf('\n%s\n', repmat('=', 1, 70));
    fprintf('  Recording %d / %d:  %s\n', iRec, numel(rec_lst), rec_name);
    fprintf('%s\n', repmat('=', 1, 70));

    % -----------------------------------------------------------------
    % Stage 1 — Preprocessing
    % -----------------------------------------------------------------
    if preproc_flag
        fprintf('  [1/3]  Preprocessing...\n');
        phy = PHY_preprocessing_v2(rec_name, source_dir, dest_dir, cfg_pth, import_flag);
    else
        fprintf('  [1/3]  Loading saved summary...\n');
        load(summary_file, 'phy');
    end

    % -----------------------------------------------------------------
    % Stage 2 — Quality assessment
    %   Tests onset responses, assigns inclusion flags, stores results
    %   in phy.brain.CPR.spks.include.
    % -----------------------------------------------------------------
    fprintf('  [2/3]  Quality assessment...\n');
    phy = PHY_quality_assessment(phy);

    save(summary_file, 'phy', '-v7.3');
    fprintf('         Saved: %s\n', summary_file);

    % -----------------------------------------------------------------
    % Stage 3 — Sort spikes by stimulus state
    %   Aligns spike trains to each RDP direction-change event and
    %   computes per-state spike density functions.
    % -----------------------------------------------------------------
    fprintf('  [3/3]  Sorting spikes by state...\n');
    state = PHY_sort_spikes_by_state(phy);

    save(state_file, 'state', '-v7.3');
    fprintf('         Saved: %s\n', state_file);

end

fprintf('\nAll recordings processed.\n');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% LOCAL FUNCTIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function state = PHY_sort_spikes_by_state(in)
% PHY_SORT_SPIKES_BY_STATE  Align spike trains and behaviour to each RDP
%                           direction-change event within a CPR cycle.
%
% For every state (direction epoch) within every CPR cycle the function
% extracts: stimulus parameters, outcome, joystick trajectories, and
% per-unit spike timestamps aligned to state onset.  A spike density
% function (alpha kernel) is also computed per unit per state.

clear state
state_cnt = 0;
stim      = in.stim;
joy       = in.joy;

for iCyc = 1:numel(stim.rdp_dir)
    for iState = 2:numel(stim.rdp_dir{iCyc})   % discard inherited direction from previous cycle

        state_cnt = state_cnt + 1;

        % --- Task flag ---------------------------------------------------
        state.cpr_solo(state_cnt) = stim.cpr_solo{iCyc};

        % --- Stimulus parameters -----------------------------------------
        state.rdp_dir(state_cnt)    = stim.rdp_dir{iCyc}(iState);
        state.rdp_dir_ts(state_cnt) = stim.rdp_dir_ts{iCyc}(iState);

        % Coherence is inherited from the most recent coherence event
        state.rdp_coh(state_cnt) = stim.rdp_coh{iCyc}( ...
            find(state.rdp_dir_ts(state_cnt) >= stim.rdp_coh_ts{iCyc}, 1, 'last'));

        % State boundaries: [onset timestamp, offset timestamp]
        is_last_state = iState == numel(stim.rdp_dir{iCyc});
        if is_last_state
            state_end = double(stim.cpr_cyle(iCyc, 2));
        else
            state_end = stim.rdp_dir_ts{iCyc}(iState + 1);
        end
        state.boundaries(state_cnt, :) = [stim.rdp_dir_ts{iCyc}(iState), state_end];
        state.dur_s(state_cnt)         = double(state_end - stim.rdp_dir_ts{iCyc}(iState)) / 1e6;
        state.cIdx(state_cnt)          = iCyc;

        % --- Feedback and outcome ----------------------------------------
        trg_idx = stim.feedback_ts{iCyc} > stim.rdp_dir_ts{iCyc}(iState) & ...
                  stim.feedback_ts{iCyc} < state_end;

        state.feedback_state_ts_raw{state_cnt} = stim.feedback_ts{iCyc}(trg_idx);

        % Feedback latency in ms and frame samples (120 Hz display)
        dt_us = stim.feedback_ts{iCyc}(trg_idx) - stim.rdp_dir_ts{iCyc}(iState);
        state.feedback_state_ms{state_cnt}    = dt_us ./ 1e3;
        state.feedback_state_smple{state_cnt} = ceil((dt_us ./ 1e3) ./ (1000/120));

        state.outcome{state_cnt}   = stim.outcome{iCyc}(trg_idx);
        state.reward_cum{state_cnt}= stim.reward_cum{iCyc}(trg_idx);
        state.score_cum{state_cnt} = stim.score_cum{iCyc}(trg_idx);

        % --- Joystick trajectories ---------------------------------------
        js_monk_idx = joy.js_monk_ts{iCyc} > stim.rdp_dir_ts{iCyc}(iState) & ...
                      joy.js_monk_ts{iCyc} < state_end;
        js_hum_idx  = joy.js_hum_ts{iCyc}  > stim.rdp_dir_ts{iCyc}(iState) & ...
                      joy.js_hum_ts{iCyc}  < state_end;

        state.js_monk_tlt{state_cnt} = joy.js_monk_tlt{iCyc}(js_monk_idx);
        state.js_monk_dir{state_cnt} = joy.js_monk_dir{iCyc}(js_monk_idx);
        state.js_hum_tlt{state_cnt}  = joy.js_hum_tlt{iCyc}(js_hum_idx);
        state.js_hum_dir{state_cnt}  = joy.js_hum_dir{iCyc}(js_hum_idx);

        % --- Spike trains per included unit ------------------------------
        for iUnit = 1:numel(in.brain.CPR.spks.include.unit_ID)

            if ~in.brain.CPR.spks.include.inclusion_flag(iUnit)
                continue
            end

            unit_str  = in.brain.CPR.spks.include.unit_ID{iUnit};
            chan_part = unit_str(1:9);    % e.g. 'ch001_neg'
            unit_part = unit_str(11:end); % e.g. 'unit2'

            dat = in.brain.CPR.spks.(chan_part).(unit_part);

            % Spike index relative to cycle onset (dat already cycle-aligned)
            cycle_onset = double(stim.cpr_cyle(iCyc, 1));
            spk_idx = dat{iCyc} > stim.rdp_dir_ts{iCyc}(iState) - cycle_onset & ...
                      dat{iCyc} < state_end - cycle_onset;

            % State-aligned spike timestamps (relative to state onset)
            state_onset_rel                       = stim.rdp_dir_ts{iCyc}(iState) - cycle_onset;
            state.spk_n.(unit_str)(state_cnt)     = sum(spk_idx);
            state.spk_ts.(unit_str){state_cnt}    = dat{iCyc}(spk_idx) - state_onset_rel;

            % Alpha-kernel spike density function over state duration
            time = 0 : 0.001 : state.dur_s(state_cnt);
            if state.spk_n.(unit_str)(state_cnt) > 0
                alpha_kern                         = fit_alpha(state.spk_ts.(unit_str){state_cnt} ./ 1e6, time);
                state.sdf.(unit_str){state_cnt}    = sum(alpha_kern, 1);
            else
                state.sdf.(unit_str){state_cnt}    = zeros(1, numel(time));
            end

            % Inclusion flag: was this cycle in the unit's analysis range?
            cyc_ids = in.brain.CPR.spks.include.cyc_id{iUnit};
            state.include.(unit_str)(state_cnt) = ismember(iCyc, cyc_ids);

        end % iUnit
    end % iState
end % iCyc

end % PHY_sort_spikes_by_state


function out = concat_coh_blocks(var_in, cbound)
% CONCAT_COH_BLOCKS  Concatenate data within coherence block boundaries.

for iBlock = 1:numel(cbound) - 1
    seg = var_in(cbound(iBlock) : cbound(iBlock+1) - 1);
    if iscell(seg)
        out{iBlock} = cell2mat(seg);
    else
        out(iBlock) = unique(seg);
    end
end

end % concat_coh_blocks


function gauss = fit_gaussian(spks, time)
% FIT_GAUSSIAN  Fit a Gaussian kernel centred on each spike time.

sigma = 0.005;   % kernel width in seconds

for iSpk = 1:numel(spks)
    mu           = spks(iSpk);
    gauss(iSpk,:)= exp(-0.5 .* ((time - mu) ./ sigma).^2) ./ (sigma * sqrt(2*pi));
end

end % fit_gaussian


function alpha = fit_alpha(spks, time)
% FIT_ALPHA  Fit a causal alpha kernel centred on each spike time.
%            Normalised to unit area for rate estimation in Hz.

tau   = 0.005;   % kernel time constant in seconds
nSpks = numel(spks);
nTime = numel(time);
alpha = zeros(nSpks, nTime);

for iSpk = 1:nSpks
    t_rel       = time - spks(iSpk);
    k           = zeros(1, nTime);
    causal      = t_rel >= 0;
    k(causal)   = (t_rel(causal) ./ tau) .* exp(1 - t_rel(causal) ./ tau);
    alpha(iSpk,:) = k / (exp(1) * tau);   % normalise to unit area
end

end % fit_alpha


function [all_spks, sdf_g, sdf_a] = FR_estimation(spike_times, time, plot_flag)
% FR_ESTIMATION  Estimate firing rate from spike times using Gaussian and
%                alpha kernel spike density functions.
%
% INPUT
%   spike_times  cell [nTrials×1]  spike timestamps in seconds per trial
%   time         [1×nSamples]      time axis in seconds
%   plot_flag    logical            true = draw raster

all_spks = [];
sdf_g    = [];
sdf_a    = [];

for iTrial = 1:numel(spike_times)
    spks     = double(spike_times{iTrial}') ./ 1e6;
    all_spks = [all_spks, spks];

    % Raster plot — each trial is a row, each spike a vertical tick
    if plot_flag && ~isempty(spks)
        xspk      = repmat(spks, 3, 1);
        yspk      = nan(size(xspk));
        yspk(1,:) = iTrial - 1;
        yspk(2,:) = iTrial;
        plot(xspk, yspk, 'Color', 'k', 'LineWidth', 1.25);
    end

    if ~isempty(spks)
        sdf_g(iTrial,:) = sum(fit_gaussian(spks, time), 1);
        sdf_a(iTrial,:) = sum(fit_alpha(spks, time),    1);
    end
end

end % FR_estimation


function out = test_onset_response(spks_cyc)
% TEST_ONSET_RESPONSE  Test whether a unit shows a significant onset
%                      response in the first 500 ms after cycle start.
%
% Uses an alpha-kernel SDF averaged across cycles.  Significance is
% assessed by a Wilcoxon signed-rank test (baseline vs stimulus window)
% and a threshold-crossing latency estimate (3 SD above/below baseline).

% Crop to first 1000 ms to keep computation fast
for iCyc = 1:numel(spks_cyc)
    spks_cyc{iCyc}(spks_cyc{iCyc} > 1e6) = [];
end

% Build average SDF across cycles
tstep = 0.001;
time  = -0.3 : tstep : 1.0;

[~, ~, sdf_a] = FR_estimation(spks_cyc, time, false);

% Safe return if no spikes found in any cycle
if isempty(sdf_a)
    out = struct('mean_fr', NaN, 'lat', NaN, 'p', NaN, 'h', NaN, ...
                 'stats', struct('zval', NaN));
    return
end

msdf = mean(sdf_a, 1);   % mean SDF across cycles

% Time windows (sample indices):  baseline = −300 to 0 ms,  stimulus = 0 to 200 ms
BL_idx   = 1  : 300;
stim_idx = 301 : 500;
out.mean_fr = mean(msdf(stim_idx));

% Wilcoxon signed-rank test on per-cycle window averages
mBL   = mean(sdf_a(:, BL_idx),   2);
mStim = mean(sdf_a(:, stim_idx), 2);
[out.p, out.h, out.stats] = signrank(mStim, mBL);

if ~isfield(out.stats, 'zval')
    out.stats.zval = NaN;
end

% Threshold-crossing latency: first run of ≥10 consecutive bins that
% all exceed the baseline mean ± 3 SD
n_std  = 3;
n_bins = 9;   % 9+1 = 10 consecutive bins required
thresh = [mean(msdf(BL_idx)) + n_std * std(msdf(BL_idx)), ...
          mean(msdf(BL_idx)) - n_std * std(msdf(BL_idx))];

exc = zeros(1, numel(time));
for s = stim_idx(1) : stim_idx(end) - n_bins
    window = msdf(s : s + n_bins);
    if all(window >= thresh(1)) || all(window <= thresh(2))
        exc(s) = s;
    end
end

first_cross = find(exc, 1, 'first');
if ~isempty(first_cross)
    out.lat = first_cross - stim_idx(1);   % latency in ms relative to stim onset
else
    out.lat = NaN;
end

end % test_onset_response


function phy = PHY_quality_assessment(phy)
% PHY_QUALITY_ASSESSMENT  Test onset responses and assign inclusion flags.
%
% For every sorted unit on every channel:
%   1. Manually define stable analysis ranges (cycle subsets).
%   2. Test onset response against baseline using a Wilcoxon test and
%      a threshold-crossing latency estimate.
%   3. Apply inclusion criteria and store results in phy.brain.CPR.spks.include.
%
% Inclusion criteria (all must be met):
%   - ≥ 30 cycles in the analysis range
%   - Significant onset response (p < 0.05, Wilcoxon signed-rank)
%   - Mean firing rate ≥ 1 Hz
%   - Onset latency between 35 and 200 ms

% Table schema
var_names  = {'unit_ID','n_Cycles','mean_FR','signrank_p','signrank_z', ...
              'thresh_latency_ms','inclusion_flag'};
var_types  = {'string','double','double','double','double','double','logical'};
t          = table('Size', [1000, numel(var_names)], ...
                   'VariableTypes', var_types, ...
                   'VariableNames', var_names);

% Inclusion thresholds
min_cycles   = 30;
min_dur_s    = 5;
min_fr       = 1;
p_thresh     = 0.05;
min_lat_ms   = 35;
max_lat_ms   = 200;

chan_lst = fieldnames(phy.brain.CPR.spks);
chan_lst(strcmp(chan_lst, 'include')) = [];

cc = 0;   % row counter

for iChan = 1:numel(chan_lst)
    unit_lst = fieldnames(phy.brain.CPR.spks.(chan_lst{iChan}));

    for iUnit = 1:numel(unit_lst)

        % Skip unsorted noise cluster
        if strcmp(unit_lst{iUnit}, 'unit0')
            continue
        end

        spk_times_cyc = phy.brain.CPR.spks.(chan_lst{iChan}).(unit_lst{iUnit});

        % Manually assign stable analysis ranges for this unit
        mask = manually_assign_analysis_range(phy, chan_lst{iChan}, unit_lst{iUnit});

        for iRange = 1:size(mask, 2)
            cc           = cc + 1;
            range_suffix = sprintf('_range%d', iRange);
            t.unit_ID(cc)= string([chan_lst{iChan} '_' unit_lst{iUnit} range_suffix]);

            cycles_in_range = spk_times_cyc(mask(:, iRange));
            n_valid         = sum(mask(:, iRange));

            if n_valid >= min_cycles
                res = test_onset_response(cycles_in_range);

                t.n_Cycles(cc)          = n_valid;
                t.cyc_id{cc}            = find(mask(:, iRange));
                t.mean_FR(cc)           = res.mean_fr;
                t.signrank_p(cc)        = res.p;
                t.signrank_z(cc)        = res.stats.zval;
                t.thresh_latency_ms(cc) = res.lat;

                % All four criteria must be satisfied for inclusion
                lat_ok  = res.lat  >  min_lat_ms && res.lat < max_lat_ms;
                p_ok    = res.p    <  p_thresh;
                fr_ok   = res.mean_fr > min_fr;
                n_ok    = n_valid  >= min_cycles;
                t.inclusion_flag(cc) = lat_ok && p_ok && fr_ok && n_ok;

            else
                % Not enough cycles — flag as excluded
                t.n_Cycles(cc)          = NaN;
                t.cyc_id{cc}            = NaN;
                t.mean_FR(cc)           = NaN;
                t.signrank_p(cc)        = NaN;
                t.signrank_z(cc)        = NaN;
                t.thresh_latency_ms(cc) = NaN;
                t.inclusion_flag(cc)    = false;
            end
        end % iRange
    end % iUnit
end % iChan

% Remove unused pre-allocated rows and store
t(ismissing(t.unit_ID), :)  = [];
phy.brain.CPR.spks.include  = t;

end % PHY_quality_assessment

%% WIP: NOT USED YET 

function out = PHY_sort_spikes_by_coherence(in)
% PHY_SORT_SPIKES_BY_COHERENCE  Group state-level data into coherence blocks.

out.coh          = [];
out.js_monk_dir  = [];
out.js_monk_tlt  = [];
out.js_hum_dir   = [];
out.js_hum_tlt   = [];
out.reward_cum   = [];
out.outcome      = [];

for iCyc = 1:in.cIdx(end)
    cIdx   = in.cIdx == iCyc;
    cbound = [find(cIdx, 1, 'first'), ...
              find(cIdx, 1, 'first') + find(diff(in.rdp_coh(cIdx))), ...
              find(cIdx, 1, 'last') + 1];

    out.coh         = [out.coh,        concat_coh_blocks(in.rdp_coh,       cbound)];
    out.js_monk_dir = [out.js_monk_dir, concat_coh_blocks(in.js_monk_dir,   cbound)];
    out.js_monk_tlt = [out.js_monk_tlt, concat_coh_blocks(in.js_monk_tlt,   cbound)];
    out.js_hum_dir  = [out.js_hum_dir,  concat_coh_blocks(in.js_hum_dir,    cbound)];
    out.js_hum_tlt  = [out.js_hum_tlt,  concat_coh_blocks(in.js_hum_tlt,    cbound)];
    out.reward_cum  = [out.reward_cum,  concat_coh_blocks(in.reward_cum,     cbound)];
end

end % PHY_sort_spikes_by_coherence

function T = convert2table(state, varargin)
% CONVERT2TABLE  Convert the state struct to a tidy table.
%
% Spike times for excluded trials are replaced with empty cells.
% Units with no valid trials can optionally be dropped.

p = inputParser;
addParameter(p, 'RemoveEmptyUnits', true, @islogical);
parse(p, varargin{:});
remove_empty = p.Results.RemoveEmptyUnits;

n_trials    = numel(state.cpr_solo);
all_fields  = fieldnames(state);
skip_fields = {'spk_ts','spk_n','include'};
data_fields = setdiff(all_fields, skip_fields);

% Build table from trial-wise scalar and cell fields
T = table();
for i = 1:numel(data_fields)
    f   = data_fields{i};
    val = state.(f);
    if (isvector(val) && numel(val) == n_trials) || ...
       (iscell(val)   && numel(val) == n_trials)
        T.(f) = val(:);
    else
        warning('convert2table: skipping field ''%s'' (unsupported size/type).', f);
    end
end

% Reorder to a fixed canonical column sequence
desired_order = {'cIdx','cpr_solo','dur_s','feedback_state_smple', ...
                 'outcome','reward_cum','rdp_coh','rdp_dir','rdp_dir_ts', ...
                 'js_hum_dir','js_hum_tlt','js_monk_dir','js_monk_tlt'};
T = T(:, desired_order);

% Append spike timestamps as one column per unit
unit_names = {};
if isfield(state, 'spk_ts')
    unit_names = fieldnames(state.spk_ts);
    for i = 1:numel(unit_names)
        T.(unit_names{i}) = state.spk_ts.(unit_names{i})(:);
    end
end

% Zero out spike columns for excluded trials
if isfield(state, 'include')
    for i = 1:numel(unit_names)
        u = unit_names{i};
        if isfield(state.include, u)
            spk_col          = T.(u);
            spk_col(~state.include.(u)(:)) = {[]};
            T.(u)            = spk_col;
        end
    end
end

% Optionally drop units that have no valid trials at all
if remove_empty && isfield(state, 'include')
    keep = false(size(unit_names));
    for i = 1:numel(unit_names)
        u       = unit_names{i};
        keep(i) = isfield(state.include, u) && any(state.include.(u));
    end
    T(:, unit_names(~keep)) = [];
    unit_names = unit_names(keep);
end

% Move spike columns to the rightmost position
existing_unit_cols = intersect(unit_names, T.Properties.VariableNames);
if ~isempty(existing_unit_cols)
    T = movevars(T, existing_unit_cols, 'After', width(T));
end

end % convert2table


function mask = manually_assign_analysis_range(phy, chan, clus)
% MANUALLY_ASSIGN_ANALYSIS_RANGE  Interactively define stable cycle ranges.
%
% Plots a raster of the first 2 s of each cycle for the given unit.
% The user enters the number of stable clusters and their cycle ranges.
% The resulting logical mask is saved to disk and reloaded on subsequent
% calls so the interactive step is skipped.

dest_dir = fullfile('/Users/cnl/Documents/DATA/Nilan/spike_sorting/', ...
    [phy.exp.date '_' phy.exp.rec_num '_' phy.exp.block], 'inclusion_mask/');

if ~isfolder(dest_dir)
    mkdir(dest_dir);
end

mask_file = fullfile(dest_dir, [chan '_' clus '.mat']);
disp([chan '_' clus]);

% Return saved mask if it already exists
if isfile(mask_file)
    load(mask_file, 'mask');
    return
end

% Crop spike trains to first 2 s for display
n_cyc = numel(phy.stim.cpr_cyle);
cpr_spk_times = cell(1, n_cyc);
for iCyc = 1:n_cyc
    ts = double(phy.brain.CPR.spks.(chan).(clus){iCyc});
    cpr_spk_times{iCyc} = ts(ts <= 2e6);
end

N = n_cyc;
time = 0 : 0.001 : 2.0;

n_non_empty = N - sum(cellfun(@isempty, cpr_spk_times));
if n_non_empty < 30
    % Too few spikes to be worth curating — exclude entirely
    mask  = false(N, 1);
    nClus = 0;
else
    figure; hold on; grid on;
    FR_estimation(cpr_spk_times, time, true);
    fprintf('  Total cycles: %d\n', N);
    nClus = input('  Number of stable clusters to define (0 = exclude all): ');
end

if nClus == 0
    mask = false(N, 1);
else
    mask = false(N, nClus);
    for i = 1:nClus
        rng_i = input(sprintf('  Range %d — enter as [start_cycle end_cycle]: ', i));
        mask(rng_i(1):rng_i(2), i) = true;
    end
end

save(mask_file, 'mask');

end % manually_assign_analysis_range