addpath /Users/fschneider/Documents/GitHub/CPR/Matlab/preprocessing/

source = '/Volumes/DPZ/KognitiveNeurowissenschaften/CNL/DATA/fxs/CPR_electrophysiology/Nilan/mwk2/';
cfg_pth	= '/Users/fschneider/Documents/GitHub/CPR/Matlab/CFG/felix_nhp_solo.cfg';
write_file = true;

var_lst     = {
    'ML_', ...
    'CTRL_', ...
    'RDP_', ...
    'INFO_', ...
    'TRIAL_', ...
    'IO_joystickDirection', ...
    'IO_joystickStrength',...
    'IO_fixation_flag',...
    'EYE_x_dva',...
    'EYE_y_dva'};

file_lst = {'20250515_nil_CPRsolo_block1_physio4.mwk2',...
    '20250515_nil_CPRsolo_block2_physio4.mwk2',...
    '20250515_nil_CPRsolo_block3_physio4.mwk2',...
    '20250509_nil_CPRsolo_block1_physio4.mwk2',...
    '20250508_nil_CPRsolo_block1_physio4.mwk2',...
    '20250407_nil_CPRsolo_block1_physio4.mwk2',...
    '20250325_nil_CPRsolo_block1_phy4.mwk2',...
    };

for iFile = 1:length(file_lst)
    CPR_import_mwk2([source fname], var_lst, write_file, cfg_pth);
end